<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="BESTOURS - Travel and Tours multipurpose template">
	<meta name="author" content="Ansonika">
	<title>BESTOURS - Travel and Tours multipurpose template</title>

	<!-- Favicons-->
	<link rel="shortcut icon" href="../img/favicon.ico" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" href="../img/apple-touch-icon-57x57-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="../img/apple-touch-icon-72x72-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="../img/apple-touch-icon-114x114-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="../img/apple-touch-icon-144x144-precomposed.png">

	<!-- GOOGLE WEB FONT -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Satisfy" rel="stylesheet">

	<!-- BASE CSS -->
	<link href="../css/animate.min.css" rel="stylesheet">
	<link href="../css/bootstrap.min.css" rel="stylesheet">
	<link href="../css/style.css" rel="stylesheet">
	<link href="../css/responsive.css" rel="stylesheet">
	<link href="../css/menu.css" rel="stylesheet">
	<link href="../css/icon_fonts/css/all_icons.min.css" rel="stylesheet">

	<!-- SPECIFC CSS -->
	<link href="../css/magnific-popup.min.css" rel="stylesheet">

	<!-- YOUR CUSTOM CSS -->
	<link href="../css/custom.css" rel="stylesheet">
</head>

<body>

	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div>
	<!-- End Preload -->

	<!-- Header================================================== -->
    <?php require $_SERVER['DOCUMENT_ROOT'] . '/parts/header.html' ?>
		<!-- End Header -->

	<!-- End Header 1-->

	<!-- SubHeader =============================================== -->
	<section class="parallax_window_in" data-parallax="scroll" data-image-src="img/sub_header_about.jpg" data-natural-width="1400" data-natural-height="470">
		<div id="sub_content_in">
			<div id="animate_intro">
				<h1>About Bestours</h1>
				<p>"Usu habeo equidem sanctus no ex melius labitur conceptam eos"</p>
			</div>
		</div>
	</section>
	<!-- End section -->
	<!-- End SubHeader ============================================ -->

	<section class="wrapper">
		<div class="divider_border"></div>

		<div class="container">
			<div class="main_title">
				<h2>Some <span>Bestours</span> info</h2>
				<p>Quisque at tortor a libero posuere laoreet vitae sed arcu. Curabitur consequat.</p>
			</div>

			<div class="row">
				<div class="col-sm-6">
					<h3>The Company</h3>
					<p>Per cu esse assentior delicatissimi, qui adipiscing dissentiunt mediocritatem in, <strong>dicat voluptaria</strong> no eam. No est alia eloquentiam. Has rebum vulputate adversarium no. Pro cibo delenit scripserit id.</p>
					<p>Sea id tantas doctus aeterno, tation mollis <strong>appetere in per</strong>, usu dicat novum eirmod ei. In sit audire equidem persecuti, eu integre alterum principes qui. Mea nominavi voluptua suscipiantur eu, ea omnis labores fuisset sed. Quo quidam vidisse constituam cu. Quo quas tibique ex.</p>
					<h4>Mission</h4>
					<p>Ex graeco nostrud theophrastus nam, cum tibique reprimique ad. Mea omittam electram te, eu cum fastidii sapientem delicatissimi. Sed cu eripuit veritus propriae. An eam choro saperet ullamcorper, eam saperet rationibus ut. Cu usu tation quaeque vocibus, alterum torquatos persequeris te ius.</p>
				</div>
				<div class="col-sm-6">
					<p class="advertise"><img src="../img/trip-advisor.jpg" alt="" class="img-responsive">
					</p>
				</div>
			</div>
			<!-- End row -->
			<hr>

			<div class="main_title_2">
				<h3>Our <span>features</span></h3>
				<p>Quisque at tortor a libero posuere laoreet vitae sed arcu. Curabitur consequat.</p>
			</div>
			<div class="row">
				<div class="col-sm-6">
					<div class="box_features">
						<i class="icon_set_1_icon-89"></i>
						<h4>Great support</h4>
						<p>Sea id tantas doctus aeterno, tation mollis <strong>appetere in per</strong>, usu dicat novum eirmod ei. In sit audire equidem persecuti, eu integre alterum principes qui. Mea nominavi voluptua suscipiantur eu, ea omnis labores fuisset sed.</p>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="box_features">
						<i class="icon_set_1_icon-61"></i>
						<h4>We speak several languages</h4>
						<p>Sea id tantas doctus aeterno, tation mollis <strong>appetere in per</strong>, usu dicat novum eirmod ei. In sit audire equidem persecuti, eu integre alterum principes qui. Mea nominavi voluptua suscipiantur eu, ea omnis labores fuisset sed.</p>
					</div>
				</div>
			</div>
			<!-- End row -->
			<div class="row">
				<div class="col-sm-6">
					<div class="box_features">
						<i class="icon_set_1_icon-13"></i>
						<h4>We take care of everyone</h4>
						<p>Sea id tantas doctus aeterno, tation mollis <strong>appetere in per</strong>, usu dicat novum eirmod ei. In sit audire equidem persecuti, eu integre alterum principes qui. Mea nominavi voluptua suscipiantur eu, ea omnis labores fuisset sed.</p>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="box_features">
						<i class="icon_set_1_icon-63"></i>
						<h4>Available on mobiles and tablets</h4>
						<p>Sea id tantas doctus aeterno, tation mollis <strong>appetere in per</strong>, usu dicat novum eirmod ei. In sit audire equidem persecuti, eu integre alterum principes qui. Mea nominavi voluptua suscipiantur eu, ea omnis labores fuisset sed.</p>
					</div>
				</div>
			</div>
			<!-- End row -->

			<hr>

			<div class="main_title_2">
				<h3>Our <span>team</span> and guides</h3>
				<p>Quisque at tortor a libero posuere laoreet vitae sed arcu. Curabitur consequat.</p>
			</div>

			<!--Team Carousel -->
			<div class="owl-carousel owl-theme team-carousel add_bottom_30">

				<div class="team-item">
					<div class="team-item-img">
						<img src="../img/team/team-1.jpg" alt="">
						<div class="team-item-detail">
							<div class="team-item-detail-inner">
								<h4>Mitchell Young</h4>
								<p>Similique sunt culpa qui officia deserunt mollitia animi dolorum fuga.</p>
								<ul class="social">
									<li><a href="#0"><i class="icon-facebook"></i></a>
									</li>
									<li><a href="#0"><i class="icon-twitter"></i></a>
									</li>
									<li><a href="#0"><i class="icon-google"></i></a>
									</li>
									<li><a href="#0"><i class="icon-linkedin"></i></a>
									</li>
								</ul>
								<a href="profile.phtml" class="btn_1 white">View porfile</a>
							</div>
						</div>
					</div>
					<div class="team-item-info">
						<h4>Mitchell Young</h4>
						<p>CEO</p>
					</div>
				</div>

				<div class="team-item">
					<div class="team-item-img">
						<img src="img/team/team-2.jpg" alt="">
						<div class="team-item-detail">
							<div class="team-item-detail-inner">
								<h4>Ronald Green</h4>
								<p>Similique sunt culpa qui officia deserunt mollitia animi dolorum fuga.</p>
								<ul class="social">
									<li><a href="#0"><i class="icon-facebook"></i></a>
									</li>
									<li><a href="#0"><i class="icon-twitter"></i></a>
									</li>
									<li><a href="#0"><i class="icon-google"></i></a>
									</li>
									<li><a href="#0"><i class="icon-linkedin"></i></a>
									</li>
								</ul>
								<a href="profile.phtml" class="btn_1 white">View porfile</a>
							</div>
						</div>
					</div>
					<div class="team-item-info">
						<h4>Ronald Green</h4>
						<p>Tourist manger</p>
					</div>
				</div>

				<div class="team-item">
					<div class="team-item-img">
						<img src="img/team/team-3.jpg" alt="">
						<div class="team-item-detail">
							<div class="team-item-detail-inner">
								<h4>Carl Peppard</h4>
								<p>Similique sunt culpa qui officia deserunt mollitia animi dolorum fuga.</p>
								<ul class="social">
									<li><a href="#0"><i class="icon-facebook"></i></a>
									</li>
									<li><a href="#0"><i class="icon-twitter"></i></a>
									</li>
									<li><a href="#0"><i class="icon-google"></i></a>
									</li>
									<li><a href="#0"><i class="icon-linkedin"></i></a>
									</li>
								</ul>
								<a href="profile.phtml" class="btn_1 white">View porfile</a>
							</div>
						</div>
					</div>
					<div class="team-item-info">
						<h4>Carl Peppard</h4>
						<p>Tourist guide</p>
					</div>
				</div>

				<div class="team-item">
					<div class="team-item-img">
						<img src="img/team/team-4.jpg" alt="">
						<div class="team-item-detail">
							<div class="team-item-detail-inner">
								<h4>Sandra Bullock</h4>
								<p>Similique sunt culpa qui officia deserunt mollitia animi dolorum fuga.</p>
								<ul class="social">
									<li><a href="#0"><i class="icon-facebook"></i></a>
									</li>
									<li><a href="#0"><i class="icon-twitter"></i></a>
									</li>
									<li><a href="#0"><i class="icon-google"></i></a>
									</li>
									<li><a href="#0"><i class="icon-linkedin"></i></a>
									</li>
								</ul>
								<a href="profile.phtml" class="btn_1 white">View porfile</a>
							</div>
						</div>
					</div>
					<div class="team-item-info">
						<h4>Sandra Bullock</h4>
						<p>Tourist guide</p>
					</div>
				</div>

			</div>
			<!--End Team Carousel-->

		</div>
		<!-- End container -->
	</section>
	<!-- End section -->

	<div class="container margin_60">
		<div class="banner">
			<h3>Sea id tantas doctus aeterno tation mollis appetere in per, usu dicat novum eirmod ei in sit audire equidem persecuti, eu integre alterum principes qui.</h3>
			<a href="#" class="btn_1 white">Explore Now</a>
		</div>
		<!-- end banner -->
	</div>
	<!-- end container -->

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-3">
					<h3>Need help?</h3>
					<a href="tel://004542344599" id="phone">+45 423 445 99</a>
					<a href="mailto:help@citytours.com" id="email_footer">help@bestours.com</a>
				</div>
				<div class="col-md-2 col-sm-3">
					<h3>About</h3>
					<ul>
						<li><a href="#">About us</a>
						</li>
						<li><a href="#">FAQ</a>
						</li>
						<li><a href="#">Login</a>
						</li>
						<li><a href="#">Register</a>
						</li>
						<li><a href="#">Terms and condition</a>
						</li>
					</ul>
				</div>
				<div class="col-md-4 col-sm-6">
					<h3>Twitter feed</h3>
					<div class="latest-tweets" data-number="10" data-username="ansonika" data-mode="fade" data-pager="false" data-nextselector=".tweets-next" data-prevselector=".tweets-prev" data-adaptiveheight="true">
						<!-- data-username="your twitter username" -->
					</div>
					<div class="tweet-control">
						<div class="tweets-prev"></div>
						<div class="tweets-next"></div>
					</div>
					<!-- End .tweet-control -->
				</div>
				<div class="col-md-3 col-sm-12">
					<h3>Newsletter</h3>
					<div id="message-newsletter_2">
					</div>
					<form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
						<div class="form-group">
							<input name="email_newsletter_2" id="email_newsletter_2" type="email" value="" placeholder="Your email" class="form-control">
						</div>
						<input type="submit" value="Subscribe" class="btn_1" id="submit-newsletter_2">
					</form>
				</div>
			</div>
			<!-- End row -->
			<hr>
			<div class="row">
				<div class="col-sm-8">
					<div class="styled-select">
						<select class="form-control" name="lang" id="lang">
							<option value="English" selected>English</option>
							<option value="French">French</option>
							<option value="Spanish">Spanish</option>
							<option value="Russian">Russian</option>
						</select>
					</div>
					<span id="copy">© BestTours 2023 - All rights reserved</span>
				</div>
				<div class="col-sm-4" id="social_footer">
					<ul>
						<li><a href="#"><i class="icon-facebook"></i></a>
						</li>
						<li><a href="#"><i class="icon-twitter"></i></a>
						</li>
						<li><a href="#"><i class="icon-google"></i></a>
						</li>
						<li><a href="#"><i class="icon-instagram"></i></a>
						</li>
					</ul>
				</div>
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</footer>
	<!-- End footer -->

	<div id="toTop"></div>
	<!-- Back to top button -->

	<!-- Search Menu -->
	<div class="search-overlay-menu">
		<span class="search-overlay-close"><i class="icon_close"></i></span>
		<form role="search" id="searchform" method="get">
			<input value="" name="q" type="search" placeholder="Search..." />
			<button type="submit"><i class="icon-search-6"></i>
			</button>
		</form>
	</div>
	<!-- End Search Menu -->

	<!-- COMMON SCRIPTS -->
	<script src="../js/jquery-3.7.0.min.js"></script>
	<script src="../js/common_scripts_min.js"></script>
	<script src="../assets/validate.js"></script>
	<script src="../js/jquery.tweet.min.js"></script>
	<script src="../js/functions.js"></script>

	<!-- SPECIFIC SCRIPTS -->
	<script>
		'use strict';
		$(".team-carousel").owlCarousel({
			items: 1,
			loop: false,
			margin: 10,
			autoplay: false,
			smartSpeed: 300,
			responsiveClass: false,
			responsive: {
				320: {
					items: 1,
				},
				768: {
					items: 2,
				},
				1000: {
					items: 3,
				}
			}
		});
	</script>

</body>

</html>