<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="BESTOURS - Travel and Tours multipurpose template">
	<meta name="author" content="Ansonika">
	<title>BESTOURS - Travel and Tours multipurpose template</title>

	<!-- Favicons-->
	<link rel="shortcut icon" href="../img/favicon.ico" type="image/x-icon">
	<link rel="apple-touch-icon" type="image/x-icon" href="../img/apple-touch-icon-57x57-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="../img/apple-touch-icon-72x72-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="../img/apple-touch-icon-114x114-precomposed.png">
	<link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="../img/apple-touch-icon-144x144-precomposed.png">

	<!-- GOOGLE WEB FONT -->
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Satisfy" rel="stylesheet">

	<!-- BASE CSS -->
	<link href="../css/animate.min.css" rel="stylesheet">
	<link href="../css/bootstrap.min.css" rel="stylesheet">
	<link href="../css/style.css" rel="stylesheet">
	<link href="../css/responsive.css" rel="stylesheet">
	<link href="../css/menu.css" rel="stylesheet">
	<link href="../css/icon_fonts/css/all_icons.min.css" rel="stylesheet">

	<!-- YOUR CUSTOM CSS -->
	<link href="../css/custom.css" rel="stylesheet">
</head>

<body>

	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div>
	<!-- End Preload -->
    <?php require $_SERVER['DOCUMENT_ROOT'] . '/parts/header.html' ?>

	<!-- SubHeader =============================================== -->
	<section class="parallax_window_in" data-parallax="scroll" data-image-src="img/sub_header_contact.jpg" data-natural-width="1400" data-natural-height="470">
		<div id="sub_content_in">
			<div id="animate_intro">
				<h1>Contact Bestours</h1>
				<p>"Usu habeo equidem sanctus no ex melius labitur conceptam eos"</p>
			</div>
		</div>
	</section>
	<!-- End section -->
	<!-- End SubHeader ============================================ -->

	<section class="wrapper add_bottom_30">
		<div class="divider_border"></div>
		<div class="container">
			<div id="map_contact" class="version_2"></div>
			<!-- end map-->
			<div class="row">

				<aside class="col-md-3">
					<div class="box_style_2">
						<h4 class="nomargin_top">Contacts info</h4>
						<p>
							11 Fifth Ave - New York, US
							<br> + 61 (2) 8093 3400
							<br>
							<a href="#">info@domain.com</a>
						</p>
						<h5>Get directions</h5>
						<form action="http://maps.google.com/maps" method="get" target="_blank">
							<div class="form-group">
								<input type="text" name="saddr" placeholder="Enter your location" class="form-control styled">
								<input type="hidden" name="daddr" value="New York, NY 11430">
								<!-- Write here your end point -->
							</div>
							<input type="submit" value="Get directions" class="btn_1 add_bottom_15">
						</form>
						<hr class="styled">
						<h4>Departmens</h4>
						<ul class="contacts_info">
							<li>Administration
								<br>
								<a href="tel://003823932342">0038 23932342</a>
								<br><a href="tel://003823932342">admin@lovefit.com</a>
								<br>
								<small>Monday to Friday 9am - 7pm</small>
							</li>
							<li>General questions
								<br>
								<a href="tel://003823932342">0038 23932342</a>
								<br><a href="tel://003823932342">questions@lovefit.com</a>
								<br>
								<p><small>Monday to Friday 9am - 7pm</small>
								</p>
							</li>
						</ul>
					</div>
				</aside>
				<!--End aside -->

				<div class="col-md-9">
					<h3>Contact us</h3>
					<p>
						Mussum ipsum cacilds, vidis litro abertis.
					</p>
					<div>
						<div id="message-contact"></div>
						<form method="post" action="/contact" id="contactform">
							<div class="row">
								<div class="col-md-6 col-sm-6">
									<div class="form-group">
										<label>First name</label>
										<input type="text" class="form-control styled" id="name_contact" name="name_contact" placeholder="Jhon">
									</div>
								</div>
								<div class="col-md-6 col-sm-6">
									<div class="form-group">
										<label>Last name</label>
										<input type="text" class="form-control styled" id="lastname_contact" name="lastname_contact" placeholder="Doe">
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6 col-sm-6">
									<div class="form-group">
										<label>Email:</label>
										<input type="email" id="email_contact" name="email_contact" class="form-control styled" placeholder="jhon@email.com">
									</div>
								</div>
								<div class="col-md-6 col-sm-6">
									<div class="form-group">
										<label>Phone number:</label>
										<input type="text" id="phone_contact" name="phone_contact" class="form-control styled" placeholder="00 44 5435435">
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-12">
									<div class="form-group">
										<label>Your message:</label>
										<textarea rows="5" id="message_contact" name="message_contact" class="form-control styled" style="height:100px;" placeholder="Hello world!"></textarea>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-md-6">
									<div class="form-group">
										<label>Are you human? 3 + 1 =</label>
										<input type="text" id="verify_contact" class=" form-control styled" placeholder=" 3 + 1 =">
									</div>
									<p>
										<input type="submit" value="Submit" class="btn_1" id="submit-contact">
									</p>
								</div>
							</div>
						</form>
					</div>
				</div>
				<!-- End col lg 9 -->
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</section>
	<!-- End section -->

	<footer>
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-3">
					<h3>Need help?</h3>
					<a href="tel://004542344599" id="phone">+45 423 445 99</a>
					<a href="mailto:help@citytours.com" id="email_footer">help@bestours.com</a>
				</div>
				<div class="col-md-2 col-sm-3">
					<h3>About</h3>
					<ul>
						<li><a href="#">About us</a>
						</li>
						<li><a href="#">FAQ</a>
						</li>
						<li><a href="#">Login</a>
						</li>
						<li><a href="#">Register</a>
						</li>
						<li><a href="#">Terms and condition</a>
						</li>
					</ul>
				</div>
				<div class="col-md-4 col-sm-6">
					<h3>Twitter feed</h3>
					<div class="latest-tweets" data-number="10" data-username="ansonika" data-mode="fade" data-pager="false" data-nextselector=".tweets-next" data-prevselector=".tweets-prev" data-adaptiveheight="true">
						<!-- data-username="your twitter username" -->
					</div>
					<div class="tweet-control">
						<div class="tweets-prev"></div>
						<div class="tweets-next"></div>
					</div>
					<!-- End .tweet-control -->
				</div>
				<div class="col-md-3 col-sm-12">
					<h3>Newsletter</h3>
					<div id="message-newsletter_2">
					</div>
					<form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
						<div class="form-group">
							<input name="email_newsletter_2" id="email_newsletter_2" type="email" value="" placeholder="Your email" class="form-control">
						</div>
						<input type="submit" value="Subscribe" class="btn_1" id="submit-newsletter_2">
					</form>
				</div>
			</div>
			<!-- End row -->
			<hr>
			<div class="row">
				<div class="col-sm-8">
					<div class="styled-select">
						<select class="form-control" name="lang" id="lang">
							<option value="English" selected>English</option>
							<option value="French">French</option>
							<option value="Spanish">Spanish</option>
							<option value="Russian">Russian</option>
						</select>
					</div>
					<span id="copy">© BestTours 2023 - All rights reserved</span>
				</div>
				<div class="col-sm-4" id="social_footer">
					<ul>
						<li><a href="#"><i class="icon-facebook"></i></a>
						</li>
						<li><a href="#"><i class="icon-twitter"></i></a>
						</li>
						<li><a href="#"><i class="icon-google"></i></a>
						</li>
						<li><a href="#"><i class="icon-instagram"></i></a>
						</li>
					</ul>
				</div>
			</div>
			<!-- End row -->
		</div>
		<!-- End container -->
	</footer>
	<!-- End footer -->

	<div id="toTop"></div>
	<!-- Back to top button -->

	<!-- Search Menu -->
	<div class="search-overlay-menu">
		<span class="search-overlay-close"><i class="icon_close"></i></span>
		<form role="search" id="searchform" method="get">
			<input value="" name="q" type="search" placeholder="Search..." />
			<button type="submit"><i class="icon-search-6"></i>
			</button>
		</form>
	</div>
	<!-- End Search Menu -->

	<!-- COMMON SCRIPTS -->
	<script src="../js/jquery-3.7.0.min.js"></script>
	<script src="../js/common_scripts_min.js"></script>
	<script src="../assets/validate.js"></script>
	<script src="../js/jquery.tweet.min.js"></script>
	<script src="../js/functions.js"></script>

	<!-- SPECIFIC SCRIPTS -->
	<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBp5eUC6orc2IlxuJwVC3wvUZoLxycJZWU&callback=Function.prototype"></script>
	<script type="text/javascript" src="../js/mapmarker.jquery.js"></script>
	<script type="text/javascript" src="../js/mapmarker_func.jquery.js"></script>
</body>

</html>